---
title: "Additional analysis"
author: "Jae Yeon Kim"
date: "1/4/2021"
output: html_document
---

# Import libs and files 

## Libs 

```{r}

if (!require(pacman)) install.packages("pacman")

pacman::p_load(tidyverse, 
               here,
               ggthemes, # Additional themes (including Stata)
               pwr, # Power analysis 
               DeclareDesign, 
               fabricatr, # Fabricate mock (fake) data  
               randomizr, # Random sampling and assignment 
               estimatr, # Fast estimation tools (IV, etc) 
               DesignLibrary) # Research design library 

```

## Files 

```{r}

# Processed data 
df <- read_csv(here("processed_data", "main_dataset_20201020.csv"))

```

# Design analysis 

## Group assignment 

The total number of observations = 1,250 

```{r}

nrow(df)

```

Four treatment conditions plus one control condition. 250 individuals were assigned to each group. 

```{r}

table(df$group)

```

## Power calculation analysis 

Acceptable level of power = 0.8/0.9 

```{r}
test_df <- data.frame("intention2report" = c(0.202, 0.0130, -0.0310, -0.0323),
                      "attitude2reply" = c(-0.0674, -0.0338, -0.0162, -0.0584),
                      "attitude2replier" = c(-0.00546, 0.0398, -0.00254, -0.0647),
                      "groups" = c("female", "female_upvoate", "male", "male_upvote"))
 
tidy_pwr_ttest <- function(effect_size){
    pwr.t.test(n = 250, d = effect_size, sig.level = 0.05, power = NULL) %>%
        tidy() %>%
        select(power)
}

power_res <- reduce(
    list( 
    test_df %>% select(groups),
        map_df(test_df$intention2report, tidy_pwr_ttest) %>%
        rename("intention2report"  = "power"),
        map_df(test_df$attitude2reply, tidy_pwr_ttest) %>%
        rename("attitude2reply"  = "power"),
        map_df(test_df$attitude2replier, tidy_pwr_ttest) %>%
        rename("attitude2replier" = "power")), 
    bind_cols)

power_res
```


```{r}

power_res %>%
    pivot_longer(cols = c(2:4),
                 names_to = "dv",
                 values_to = "obs") %>%
    ggplot(aes(x = dv, y = obs, fill = groups)) +
        geom_col(position = "dodge") +
        geom_hline(yintercept = c(0.8), 
                   linetype = "dashed") +
        labs(x = "Outcome variables", 
             y = "Power", 
             fill = "Groups") +
        theme_classic()

ggsave(here("outputs", "power_cal.png"))

```

