---
title: "Data analysis"
author: "Jae Yeon Kim"
date: "`r Sys.Date()`"
output: html_document
---

# Import libs and files 

## Libs 

```{r}
if (!require(pacman)) install.packages("pacman")

pacman::p_load(tidyverse,
               naniar,
               here,
               purrr,
               glue,
               ggthemes,
               ggrepel,
               DeclareDesign,
               patchwork)

source(here("functions", "utils.r"))

theme_set(theme_clean())
```

## Files 

```{r message=TRUE, warning=TRUE, include=FALSE}
# Processed data 
df <- read_csv(here("processed_data", "main_dataset_20201020.csv"))
```

# Data wrangling 

## Scaling 

```{r}
# Factorize group variable
df$group <- as.factor(df$group)

# Use a -1 to -1 scale.
df <- df %>%
    mutate(across(matches("comm|reply|youtube|law"), ~scales::rescale(.x, c(-1,1))))

write.csv(df, here("processed_data", "standardized.csv"))
```

## Missing (or non-applicalbe) data 

`reply_` data are not missing. The control group respondents were not exposed to this feature.

```{r}
vis_miss(df)
```

# Statistical analysis 

## Difference-in-means 

```{r}
# Create a series of name vectors 
comment_vec <- names(df)[str_detect(names(df), "comm")]
reply_vec <- names(df)[str_detect(names(df), "reply_attitude|reply_socialnorm|reply_user_attitude")]
youtube_vec <- names(df)[str_detect(names(df), "youtube")]
law_vec <- names(df)[str_detect(names(df), "law")]
metoo_vec <- names(df)[str_detect(names(df), "metoo")]

# Applying the function to the treatment groups and name vectors 
## Create the vector of names 
names <- c("comment", "reply", "youtube", "law")
## Create copying and pasting code
glue("{names}_summ <- apply_mean_diff(2:5, {names}_vec)")

comment_summ <- apply_mean_diff(2:5, comment_vec)
reply_summ <- map_dfr(seq(reply_vec), apply_mean_diff_reply)
youtube_summ <- apply_mean_diff(2:5, youtube_vec)
law_summ <- apply_mean_diff(2:5, law_vec)
metoo_summ <- map_dfr(2:5, ~custom_mean_diff(., metoo_vec))

reply_term <- c("Female upvote", "Male upvote", "Base comparison", "Upvote comparison")

reply_summ$term <- rep(reply_term, length(reply_vec))

reply_summ <- reply_summ %>% 
    filter(!str_detect(term, "comparison"))
```

## Visualization 

Individual plots except reply

```{r}
comment_plot <- custom_group_plot(comment_summ, "Comment", rev(c("Attitude on Comment = Hate Speech", "Willingness to Report", "Attitude on Commenter", "Willingness to Like", "Atttidue on Comment")))

ggsave(here("outputs", "comment_summ.png"), width = 11)

reply_plot <- custom_group_plot(reply_summ, "Reply", rev(c("Many upvotes", "Willingness to Like", "Peer pressure", "Real name", "Willingness to Report", "Attitude on Replier", "Attitude on Reply")), 4) +
    labs(subtitle = glue("Difference in means between treatment group"))

ggsave(here("outputs", "reply_summ.png"), width = 11)

platform_plot <- custom_group_plot(youtube_summ, "Platform", rev(c("Attitude on Gov Regulation", "Attitude on Self-regulation", "Attitude on YouTube")))

ggsave(here("outputs", "youtube_summ.png"), width = 11)

law_plot <- custom_group_plot(law_summ, "Legislation", rev(c("Gender Discrimination Law", "Social Media Regulation")), 4)

ggsave(here("outputs", "law_summ.png"), width = 11)

metoo_plot <- custom_group_plot(metoo_summ, "Social Movement", c("Attitude on #MeToo Movement"), 4)

ggsave(here("outputs", "metoo_summ.png"), width = 11)
```

The comprehensive one 

```{r}
(comment_plot / reply_plot) + plot_annotation(tag_levels = "A")

ggsave(here("outputs", "comment_reply.png"), height = 7, width = 10)
```

```{r}
(platform_plot / law_plot) + plot_annotation(tag_levels = 'A')
    
ggsave(here("outputs", "else_summ.png"), height = 8, width = 12)
```

## Conditional treatment effect 

### CATE

```{r}
nested_df <- df %>% 
    mutate(age_fac = if_else(age >= median(age), "Old", "Young")) %>%
    mutate(male_fac = recode(male, 
                         `1` = "Male",
                         `0` = "Female")) %>%
    group_by(factor(male_fac), factor(age_fac)) %>%
    nest()

cate <- map_dfr(2:5, ~est_cate(nested_df, .)) 

cate_model_out <- map_dfr(cate$model, unnest) %>%
    select(term, estimate, conf.low, conf.high, outcome) %>%
    mutate(group = cate$group,
           male = cate$`factor(male_fac)`,
           age = cate$`factor(age_fac)`)

cate_model_out %>%
    mutate(group = recode(group,
                     `2` = "Female",
                     `3` = "Female + Upvotes",
                     `4` = "Male",
                     `5` = "Male + Upvotes")) %>%
    ggplot(aes(x = group, y = estimate, ymax = conf.high, ymin = conf.low)) +
        geom_pointrange() +
        labs(title = "Willingness to Report",
         y = "Estimate",
         x = "",
         subtitle = "Difference in means between control and treatment groups") +
        facet_grid(male~age) +
        geom_hline(yintercept = 0, linetype = 'dashed', col = 'red') +
        coord_flip()

ggsave(here("outputs", "cate.png"))
```